return {
  enabled = true,
	"folke/which-key.nvim",
	event = "VeryLazy",
	opts = {
    icons = {
      mappings = false,
      keys = {
          Up = "Up",
          Down = "Down",
          Left = "Left",
          Right = "Right",
          C = "C",
          M = "M",
          D = "D",
          S = "S",
          CR = "CR",
          Esc = "Esc",
          ScrollWheelDown = "ScrollWheelDown",
          ScrollWheelUp = "ScrollWheelUp",
          NL = "NL",
          BS = "BS",
          Space = "Space",
          Tab = "Tab",
          F1 = "F1",
          F2 = "F2",
          F3 = "F3",
          F4 = "F4",
          F5 = "F5",
          F6 = "F6",
          F7 = "F7",
          F8 = "F8",
          F9 = "F9",
          F10 = "F10",
          F11 = "F11",
          F12 = "F12",
      },
    },
	  defaults = {},
		spec = {
		  {
			  mode = { "n", "v" }, 
        { "<leader>n", group = "Neotree"},
        { "<leader>f", group = "Telescope"},
        { "<leader>e", group = "Toggle"},
        { "<leader>y", group = "Yank"},
        { "<leader>r", group = "Replace"},
        { "<leader>v", group = "Verilog"},
        { "<leader>s", group = "Sessions"},
			},
		},
  },
} 
